TeenFlightInventory/urls.py
from datetime import datetime

from django.conf.urls import url, include
import django.contrib.auth.views

import main.forms
import main.urls

import inv.urls

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'main/login.html',
            'authentication_form': main.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^', include(main.urls)),
    url(r'^inv/', include(inv.urls)),
]

inv/urls.py
from django.conf.urls import url

import inv.views

app_name = 'inv'
urlpatterns = [
    url(r'^$', inv.views.home, name='home'),
    url(r'^add/$', inv.views.new_transaction, name='new_transaction'),
    url(r'^view/(?P<id>[0-9]+)/$', inv.views.view_transaction, name='view_transaction'),
    url(r'^edit/(?P<id>[0-9]+)/$', inv.views.edit_transaction, name='edit_transaction'),
]

inv/models.py
from django.db import models

from django.contrib.auth.models import User


class Transaction(models.Model):
    # id field w/ auto-increment foreign key automatically set by django

    time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, unique=False)
    approved = models.BooleanField(default=False)

    def getParts(self):
        return PartChange.objects.filter(transaction=self)

    def __str__(self):
        return '%s|%s' % (self.id, self.getParts())

    @property
    def parts(self):
        parts_all = self.getParts()
        parts_len = parts_all.count()

        if parts_len > 5:
            parts = [p.part_number for p in self.getParts()[:4]]
            parts.append('...')
        else:
            parts = [p.part_number for p in self.getParts()[:5]]

        return ', '.join(parts)

    @property
    def parts_all(self):
        return ', '.join(self.getParts())


# In the future, we might want to make it so that the same part does not get multiple entries in different transactions
class PartChange(models.Model):
    # Currently, each PartChange is tied to a specific transaction
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)

    name = models.CharField(max_length=75, blank=False)
    part_number = models.CharField(max_length=20, blank=False)
    location = models.CharField(max_length=20, blank=True)
    quantity = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return '%s|%s|%s' % (self.id, self.name, self.part_number)

inv/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import StrictButton


class TransactionSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=True)

    def __init__(self, *args, **kwargs):
        super(TransactionSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_class = 'form-inline pull-right'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.layout = Layout(
            'search',
            StrictButton('Search', css_class='btn-default', type='submit'),
        )


class PartChangeForm(forms.Form):
    name = forms.CharField(max_length=75, required=True)
    part_number = forms.CharField(max_length=20, required=True)
    quantity = forms.IntegerField(required=True)
    location = forms.CharField(max_length=20, required=False)


class PartChangeFormSet(forms.BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(PartChangeFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


class PartChangeFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(PartChangeFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'POST'
        self.render_required_fields = True

inv/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory
from django.db import IntegrityError, transaction as db_transaction

from crispy_forms.layout import Submit
from django_tables2 import RequestConfig

from .forms import PartChangeForm, PartChangeFormSet, PartChangeFormSetHelper, TransactionSearchForm
from .models import PartChange, Transaction
from .tables import TransactionViewTable, PartChangeTable


def home(request):
    assert isinstance(request, HttpRequest)

    results = Transaction.objects.filter(approved=True)

    # search = ''

    if request.method == 'POST':
        search_form = TransactionSearchForm(request.POST)

        # if search_form.is_valid():
        # search = search_form.cleaned_data['search']
        # TODO: filter the queryset with the search term
    else:
        search_form = TransactionSearchForm()

    table = TransactionViewTable(results, order_by='-time')
    RequestConfig(request, paginate={'per_page': 10}).configure(table)
    context = {'title': 'Inventory', 'table': table, 'search_form': search_form}

    return render(request, 'inv/index.html', context)


def view_transaction(request, id):
    try:
        transaction = Transaction.objects.get(id=id)
        parts = transaction.getParts()
    except (Transaction.DoesNotExist, ValueError):
        # Error - invalid page, return to home
        return HttpResponseRedirect(reverse('inv:home'))

    table = PartChangeTable(parts)
    RequestConfig(request, paginate={'per_page': 10}).configure(table)
    context = {'title': 'Transaction Detail', 'table': table, 'transaction': transaction}

    return render(request, 'inv/view_transaction.html', context)


def edit_transaction(request, id):
    transaction = Transaction.objects.get(id=id)

    # Only the user that made the transaction can edit it
    if not request.user == transaction.user:
        return HttpResponseRedirect(reverse('inv:view_transaction', args=[id]))

    PartInlineFormSet = inlineformset_factory(Transaction, PartChange, fields=('name', 'location', 'part_number'))

    if request.method == "POST":
        formset = PartInlineFormSet(request.POST, request.FILES, instance=transaction)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('inv:view_transaction', args=[id]))
    else:
        formset = PartInlineFormSet(instance=transaction)

    # Helper for formatting inline formset with crispy forms
    helper = PartChangeFormSetHelper()
    helper.template = 'inv/table_inline_formset_js.html'
    helper.form_class = 'part-formset'
    helper.add_input(Submit("submit", "Save"))

    context = {
        'title': 'Edit Transaction',
        'part_formset': formset,
        'helper': helper
    }

    return render(request, 'inv/edit_transaction.html', context)


@login_required
def new_transaction(request):
    # Create the formset, specifying the form and formset we want to use.
    partchangeformset = formset_factory(PartChangeForm, min_num=1, extra=0, formset=PartChangeFormSet)

    if request.method == 'POST':
        part_formset = partchangeformset(request.POST)

        if part_formset.is_valid():
            transaction = Transaction
            new_parts = []

            for part_form in part_formset:
                name = part_form.cleaned_data.get('name')
                part_number = part_form.cleaned_data.get('part_number')
                location = part_form.cleaned_data.get('location')

                if name and part_number:
                    new_parts.append(PartChange(transaction=transaction, name=name,
                                                part_number=part_number, location=location))

            try:
                with db_transaction.atomic():
                    PartChange.objects.bulk_create(new_parts)
                    messages.success(request, 'You have submitted a transaction.')
                    return HttpResponseRedirect(reverse('inv:home'))

            except IntegrityError:  # If the transaction failed
                messages.error(request, 'There was an error saving your transaction.')
                return HttpResponseRedirect(reverse('inv:new_transaction'))

    else:
        part_formset = partchangeformset(initial=[{'quantity': 1}])

    # Helper for formatting inline formset with crispy forms
    helper = PartChangeFormSetHelper()
    helper.template = 'inv/table_inline_formset_js.html'
    helper.form_class = 'part-formset'
    helper.add_input(Submit("submit", "Save"))

    context = {
        'title': 'New Transaction',
        'part_formset': part_formset,
        'helper': helper,
    }

    return render(request, 'inv/new_transaction.html', context)

inv/templates/inv/edit_transaction.html
{% extends "main/layout.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Edit Transaction</h1>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<form id="transaction_form" method="post" action="">
    {% csrf_token %}

    {{ transaction_form|crispy }}

    <hr/>

    {{ part_formset.management_form }}

    <h2>Parts:</h2>

    {% crispy part_formset helper%}

</form>


{% endblock %}

inv/templates/inv/index.html
{% extends "main/layout.html" %}

{% block content %}

{% load crispy_forms_tags %}

<h1>
  <span>TeenFlight Inventory</span>
  <a class='btn btn-primary pull-right' href="{% url 'inv:new_transaction' %}">New Transaction</a>
</h1>

<hr/>

<span>
    {% crispy search_form %}
    <h1><span class="label label-default">Transactions:</span></h1>
</span>

<br/>

<div class='container'>
{% load django_tables2 %}
 {% render_table table %}
</div>

{% endblock %}

inv/templates/inv/new_transaction.html
{% extends "main/layout.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Create New Transaction</h1>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<form id="transaction_form" method="post" action="">
    {% csrf_token %}

    <hr/>

    {{ part_formset.management_form }}

    <h2>Parts:</h2>

    {% crispy part_formset helper%}

</form>


{% endblock %}

inv/templates/inv/table_inline_formset_js.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load crispy_forms_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table table-striped table-condensed">
        <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th for="{{ field.auto_id }}" class="control-label {% if field.field.required and not field|is_checkbox %}requiredField{% endif %}">
                                {{ field.label|safe }}{% if field.field.required and not field|is_checkbox %}<span class="asteriskField">*</span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                    <th>
                    </th>
                </tr>
            {% endif %}
        </thead>

        <tbody>
            {% for form in formset %}
                    {% if form_show_errors and not form.is_extra %}
                        {% include "bootstrap/errors.html" %}
                    {% endif %}

                    <tr class='part-formset'>
                        {% for field in form %}
                            {% include 'bootstrap/field.html' with tag="td" form_show_labels=False %}
                        {% endfor %}
                        <td/>

                    </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if inputs %}
        <div class="form-actions">
            {% for input in inputs %}
                {% include "bootstrap/layout/baseinput.html" %}
            {% endfor %}
        </div>
    {% endif %}
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

<script src="{% static 'main/scripts/jquery-1.10.2.js' %}"></script>
<script src="{% static 'main/scripts/jquery.formset.js' %}"></script>
<script>
    $('.part-formset').formset({
        addText: 'Add Part',
        deleteText: 'Remove'
    });
</script>

inv/templates/inv/transaction.html
{% extends "main/layout.html" %}

{% block content %}

{% load crispy_forms_tags %}


<h1><span class="label label-default">Transaction Info:</span></h1>

<div class="table-container">  
    <table class="table"> 
        <thead>
            <tr>                  
                <th>ID</th>
                <th>Time</th>
                <th>User</th>
                <th>Approved</th>
            </tr>
            </thead>  
            <tbody>    
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.time }}</td>
                    <td>{{ transaction.user }}</td>
                    <td><span class="{{ transaction.approved }}">✘</span></td>
                </tr>                              
            </tbody>
    </table>
</div>

<hr/>

<h3><span class="label label-default">Parts:</span></h3>

<div class='container'>
{% load django_tables2 %}
 {% render_table table "django_tables2/bootstrap.html" %}
</div>

{% endblock %}

inv/templates/inv/transaction_form.html
{% extends "main/layout.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Create New Transaction</h1>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<form id="transaction_form" method="post" action="">
    {% csrf_token %}

    {{ transaction_form|crispy }}

    <hr/>

    {{ part_formset.management_form }}

    <h2>Parts:</h2>

    {% crispy part_formset helper%}

</form>


{% endblock %}

inv/templates/inv/view_transaction.html
{% extends "main/layout.html" %}

{% block content %}

{% load crispy_forms_tags %}

<h1>
    <span class="label label-default">Transaction Info:</span>

    {% if user.is_authenticated %}
        {% if user.get_username == transaction.user.username %}
            <a class='btn btn-primary pull-right' href="{% url 'inv:edit_transaction' id=transaction.id %}">Edit</a>
        {% endif %}
    {% endif %}
</h1>

<div class="table-container">  
    <table class="table"> 
        <thead>
            <tr>                  
                <th>ID</th>
                <th>Time</th>
                <th>User</th>
                <th>Approved</th>
            </tr>
            </thead>  
            <tbody>    
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.time }}</td>
                    <td>{{ transaction.user }}</td>
                    <td><span class="{{ transaction.approved }}">✘</span></td>
                </tr>                              
            </tbody>
    </table>
</div>

<hr/>

<h3><span class="label label-default">Parts:</span></h3>

<div class='container'>
{% load django_tables2 %}
 {% render_table table "django_tables2/bootstrap.html" %}
</div>

{% endblock %}