TeenFlightInventory/urls.py
from datetime import datetime

from django.conf.urls import url, include
import django.contrib.auth.views

import main.forms
import main.urls

import inv.urls

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'main/login.html',
            'authentication_form': main.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^', include(main.urls)),
    url(r'^inv/', include(inv.urls)),
]

inv/urls.py
from django.conf.urls import url

import inv.views

app_name = 'inv'
urlpatterns = [
    url(r'^$', inv.views.home, name='home'),
    url(r'^add/$', inv.views.new_transaction, name='new_transaction'),
    url(r'^view/(?P<id>[0-9]+)/$', inv.views.view_transaction, name='view_transaction'),
    url(r'^edit/(?P<id>[0-9]+)/$', inv.views.edit_transaction, name='edit_transaction'),
]

main/urls.py
from django.conf.urls import url

import main.views

app_name = 'main'
urlpatterns = [
    url(r'^$', main.views.home, name='home'),
]

main/models.py
from django.db import models

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

main/views.py
"""
Definition of views.
"""
from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse


def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)

    context = {}

    return render(request,
                  'main/index.html',
                  context)

main/templates/main/layout.html
<!DOCTYPE html>
<html>
{% load auth_tags %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - TeenFlight</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/content/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'main/content/site.css' %}" />
        <script src="{% static 'main/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">TeenFlight</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'inv:home' %}">Inventory</a></li>
                </ul>
                {% include 'main/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {% now "Y" %} - TeenFlight Portland</p>
        </footer>
    </div>

    <script src="{% static 'main/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'main/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'main/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

main/templates/main/login.html
{% extends "main/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'home/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

main/templates/main/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}