TeenFlightInventory/urls.py
from datetime import datetime

from django.conf.urls import url, include
import django.contrib.auth.views

import main.forms
import main.urls

import inv.urls

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'main/login.html',
            'authentication_form': main.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^', include(main.urls)),
    url(r'^inv/', include(inv.urls)),
]

inv/urls.py
from django.conf.urls import url

import inv.views

app_name = 'inv'
urlpatterns = [
    url(r'^$', inv.views.home, name='home'),
    url(r'^add/$', inv.views.new_transaction, name='new_transaction'),
    url(r'^view/(?P<id>[0-9]+)/$', inv.views.view_transaction, name='view_transaction'),
    url(r'^edit/(?P<id>[0-9]+)/$', inv.views.edit_transaction, name='edit_transaction'),
]

main/urls.py
from django.conf.urls import url

import main.views

app_name = 'main'
urlpatterns = [
    url(r'^$', main.views.home, name='home'),
]

plans/urls.py
from django.conf.urls import url

import plans.forms
import plans.views

app_name = 'plans'
urlpatterns = [
    url(r'^$', plans.views.home, name='home'),
    url(r'^view/(?P<section_number>[0-9][0-9]?[A-Z]?)/$', plans.views.section, name='section'),
    url(r'^view/(?P<section_number>[0-9][0-9]?[A-Z]?)/(?P<page_number>[0-9][0-9]?)/(?P<step_number>[0-9][0-9]?)/$',
        plans.views.step, name='step'),
    url(r'^upload/$', plans.views.upload, name='upload'),
    url(r'^confirm/$', plans.views.confirm, name='confirm'),
    url(r'^progress/$', plans.views.progress, name='progress'),
    url(r'^view/(?P<section_number>[0-9][0-9]?[A-Z]?)/(?P<page_number>[0-9][0-9]?)/(?P<step_number>[0-9][0-9]?)/update/$',
        plans.views.update, name='update'),
]

plans/models.py
from django.db import models
from django.contrib.auth.models import User


class Kit(models.Model):
    name = models.CharField(max_length=75, unique=True)

    def __str__(self):
        return self.name

    def getSections(self):
        return Section.objects.filter(kit=self).order_by('section_number')

    def getConfirmedSections(self):
        return Section.objects.filter(kit=self, confirmed=True).order_by('section_number')

    def getCleanedName(self):
        return self.name.replace(' ', '-').replace('/', '-')


class Section(models.Model):
    kit = models.ForeignKey(Kit, on_delete=models.CASCADE, null=False)
    section_number = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=75)
    confirmed = models.BooleanField(default=True)

    def __str__(self):
        return "Section %s: %s" % (str(self.section_number), self.name)

    def getPages(self):
        return Page.objects.filter(section=self).order_by('page_number')

    def getConfirmedPages(self):
        return Page.objects.filter(section=self, confirmed=True).order_by('page_number')


class Page(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    page_number = models.CharField(max_length=2)
    confirmed = models.BooleanField(default=True)

    def __str__(self):
        return "%s-%s" % (str(self.section.section_number), str(self.page_number))

    def getSteps(self):
        return Step.objects.filter(page=self).order_by('step_number')

    def getConfirmedSteps(self):
        return Step.objects.filter(page=self, confirmed=True).order_by('step_number')

    def getCompletionStatus(self):
        verified = Step.objects.filter(page=self, status='V').count()
        total = self.getSteps().count()
        return "%s/%s Steps Verified" % (verified, total)


class Step(models.Model):
    STATUS_CHOICES = (
        ('I', 'Incomplete'),
        ('S', 'Started'),
        ('B', 'Blocked'),
        ('C', 'Completed'),
        ('V', 'Verified'),
    )
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    step_number = models.PositiveIntegerField()
    step_text = models.TextField()
    confirmed = models.BooleanField(default=True)
    date_completed = models.DateField(null=True, blank=True)
    date_verified = models.DateField(null=True, blank=True)

    # user_completed
    # mentor_verified

    # Step status can be accessed by get_status_display()
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='I')

    def __str__(self):
        return "Step " + str(self.step_number)

    def getNotes(self):
        return Step_Note.objects.filter(step=self).order_by('date_created')

    def getStatusStyle(self):
        if self.status is 'I':
            return ''
        elif self.status is 'S':
            return 'active'
        elif self.status is 'B':
            return 'danger'
        elif self.status is 'C':
            # 'info' is not working for some reason?
            return 'warning'
        elif self.status is 'V':
            return 'success'

    def getStatus(self):
        if self.status is 'I':
            return 'Incomplete'
        elif self.status is 'S':
            return 'Started'
        elif self.status is 'B':
            return 'Blocked'
        elif self.status is 'C':
            return 'Completed'
        elif self.status is 'V':
            return 'Verified'


class Step_Note(models.Model):
    step = models.ForeignKey(Step)
    user = models.ForeignKey(User, editable=False)
    text = models.TextField()
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return "[%s] %s: %s" % (self.date_created, self.user.username, self.text)

plans/forms.py
from django import forms

from .models import Step


class CSVUploadForm(forms.Form):
    file = forms.FileField()
    auto_confirm = forms.BooleanField(initial=True, required=False)


class StepStatusForm(forms.Form):
    status = forms.ChoiceField(choices=Step.STATUS_CHOICES, label="", initial='', widget=forms.Select(), required=True)
    new_note = forms.CharField(required=False, strip=True)

plans/views.py
"""
Plans Views
"""
from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse

from .models import Kit, Section, Page, Step, Step_Note
from .forms import CSVUploadForm, StepStatusForm

from .csvmanager import *


def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)

    context = {'title': 'Plans'}

    kits = Kit.objects.filter().order_by('name')
    context['kits'] = kits

    return render(request,
                  'plans/index.html',
                  context)


def section(request, section_number):
    context = {}
    template = 'plans/section.html'

    try:
        section = Section.objects.get(section_number=section_number)
        pages = section.getConfirmedPages()
    except (Section.DoesNotExist, ValueError):
        # Error - invalid page, return to list of sections
        return HttpResponseRedirect(reverse('home'))
    else:
        context['section'] = section
        context['pages'] = pages
        context['title'] = 'Section ' + section_number

    return render(request, template, context)


def step(request, section_number, page_number, step_number):
    context = {}
    template = 'plans/step.html'

    try:
        section = Section.objects.get(section_number=section_number)
        page = Page.objects.get(section=section, page_number=page_number)
        step = Step.objects.get(page=page, step_number=step_number)
    except (Step.DoesNotExist, ValueError):
        # Error - invalid page, return to list of sections
        return HttpResponseRedirect(reverse('plans:home'))
    else:
        context['section'] = section
        context['page'] = page
        context['step'] = step
        context['title'] = 'Step %s-%s-%s' % (section_number, page_number, step_number)

    return render(request, template, context)


def upload(request):
    context = {'title': 'Plans Upload'}
    template = 'plans/upload.html'

    if request.method == 'POST':
        form = CSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            auto_confirm = form.cleaned_data['auto_confirm']
            csvmanager.process_uploaded_csv(
                request.FILES['file'], auto_confirm)

            if auto_confirm:
                return HttpResponseRedirect(reverse('plans:home'))
            else:
                return HttpResponseRedirect(reverse('plans:confirm'))
    else:
        form = CSVUploadForm()

    context['form'] = form
    return render(request, template, context)


def confirm(request):
    context = {'title': 'Plans Confirm'}
    template = 'plans/confirm.html'

    sections = Section.objects.filter(confirmed=False)
    context['sections'] = sections

    return render(request, template, context)


def progress(request):
    context = {'title': 'Plans Progress'}
    template = 'plans/progress.html'

    return render(request, template, context)


def update(request, section_number, page_number, step_number):
    context = {'title': 'Step Update'}
    template = 'plans/step_update.html'

    try:
        section = Section.objects.get(section_number=section_number)
        page = Page.objects.get(section=section, page_number=page_number)
        step = Step.objects.get(page=page, step_number=step_number)
    except (Step.DoesNotExist, ValueError):
        # Error - invalid page, return to list of sections
        return HttpResponseRedirect(reverse('plans:home'))
    else:
        context['section'] = section
        context['page'] = page
        context['step'] = step

        if request.method == 'POST':
            form = StepStatusForm(request.POST)
            if form.is_valid():
                status = form.cleaned_data['status']
                step.status = status
                step.save()

                new_note = form.cleaned_data['new_note']

                if new_note:
                    step_note = Step_Note(step=step, user=request.user, text=new_note)
                    step_note.save()

                return HttpResponseRedirect(reverse('plans:step',
                       kwargs={'section_number': section_number, 'page_number': page_number, 'step_number': step_number}))
        else:
            form = StepStatusForm(initial={'status': step.status})

        context['form'] = form

    return render(request, template, context)

plans/templates/plans/confirm.html
{% extends "main/layout.html" %}

{% block content %}

<div>
    <h1>Plans Import Confirmation</h1>
</div>

{% for section in sections %}
    <div>
        <a class="btn-link" href="{% url "section" section_number=section.section_number %}" value="{{section}}">{{section}}</a>
    </div>
{% endfor %}

{% endblock %}



plans/templates/plans/index.html
{% extends "main/layout.html" %}
{% block content %}
<div>
    <!-- Breadcrumb hierarchy -->
    <ol class="breadcrumb">
        <li><a href="{% url "main:home" %}">Home</a></li>
        <li class="active">Plans</li>
    </ol>
</div>

    <h1> Teen Flight Master Plans Tracker</h1>

{% for kit in kits %}
    <!-- Outer accordion for this kit -->
    <div class="panel-group" id="accordion_kit_{{kit.getCleanedName}}">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <!-- Collapse object/link for this kit -->
                    <a data-toggle="collapse" data-parent="#accordion_kit_{{kit.getCleanedName}}"
                       href="#collapse_kit_{{kit.getCleanedName}}">
                        {{kit}}
                    </a>
                </h4>
            </div>

            <!-- Inner accordion for sections in the kit-->
            <div id="collapse_kit_{{kit.getCleanedName}}" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="panel-group" id="accordion_kit_{{kit.getCleanedName}}">
                        {% if kit.getConfirmedSections.count > 0 %}
                            {% for section in kit.getConfirmedSections %}
                            <!-- Outer accordion for this section -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <!-- Collapse object/link for this section -->
                                        <a data-parent="#accordion_section_{{section.section_number}}"
                                           href="{% url "plans:section" section_number=section.section_number %}">
                                            {{section}}
                                        </a>
                                    </h4>
                                </div>
                            </div>
                            <!-- endfor for section loop-->
                            {% endfor %}
                        {% else %}
                            <!-- Outer accordion for this section -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <!-- Collapse object/link for this section -->
                                        <a data-parent="#accordion_section_{{section.section_number}}">
                                            This kit has no sections yet!
                                        </a>
                                    </h4>
                                </div>
                            </div>
                            <!-- endfor for section loop-->
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- endfor for kit loop-->
{% endfor %}
{% endblock %}

plans/templates/plans/section.html
{% extends "main/layout.html" %}

{% block content %}

<div>

    <!-- Breadcrumb hierarchy -->
    <ol class="breadcrumb">
        <li><a href="{% url 'main:home' %}">Home</a></li>
        <li><a href="{% url 'plans:home' %}">Plans</a></li>
        <li class="active">{{ section }}</li>
    </ol>

    <div class="page-header">
        <h1>{{ section }}</h1>

        {% if not section.confirmed %}
        <p class="label label-danger">Warning: This section is not yet confirmed! Please confirm this section to allow it to be displayed.</p>
        {% endif %}
    </div>

</div>

{% for page in pages %}
<!-- Outer accordion for this kit -->
<div class="panel-group" id="accordion_page_{{page}}">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <!-- Collapse object/link for this kit -->

                    <div class="row">
                        <div class="col-xs-6">
                            <a data-toggle="collapse" data-parent="#accordion_page_{{page}}"
                               href="#collapse_page_{{page}}">
                                Page {{page}}
                            </a>
                        </div>
                        <div class="col-xs-6">
                            <div class="pull-right">
                                {{page.getCompletionStatus}}
                            </div>
                        </div>
                    </div>

            </div>
        </div>

        <!-- Inner accordion for sections in the kit-->
        <div id="collapse_page_{{page}}" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Step Number</th>
                            <th>Status</th>
                            <th>Date Completed</th>
                            <th>Completed By</th>
                            <th>Date Verified</th>
                            <th>Verified By</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for step in page.getConfirmedSteps %}
                        <tr class="{{step.getStatusStyle}}">
                            <td>
                                <a href="{% url "plans:step" section_number=section.section_number page_number=page.page_number step_number=step.step_number %}">
                                    {{step.step_number}}
                                </a>
                            </td>
                            <td>{{step.get_status_display}}</td>
                            <td>{{step.date_completed}}</td>
                            <td></td>
                            <td>{{step.date_verified}}</td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

plans/templates/plans/step.html
{% extends "main/layout.html" %}

{% block content %}

{% load staticfiles %}
<div>
<!-- Breadcrumb hierarchy -->
<ol class="breadcrumb">
  <li><a href="{% url "main:home" %}">Home</a></li>
  <li><a href="{% url "plans:home" %}">Plans</a></li>
  <li><a href="{% url "plans:section" section_number=section.section_number %}">{{section}}</a></li>
  <li class="active">{{page.page_number}}-{{step.step_number}}</li>
</ol>

    <div class="page-header">
      <div class="row">
        <div class="col-xs-8">
          <h1>{{ page }}: {{ step }}</h1>
        </div>
        <div class="col-xs-4">
         <a href="{% url "plans:update" section_number=section.section_number page_number=page.page_number step_number=step.step_number %}"
         class="btn btn-default" role="button">
          Update
         </a>
        </div>
      </div>
        
      {% if not step.confirmed %}
        <p class="label label-danger">Warning: This section is not yet confirmed! Please confirm this section to allow it to be displayed.</p>
      {% endif %}
    </div>

    <h3>Status: {{step.getStatus}}</h3> <br/>

    <p>{{ step.step_text|linebreaks }}</p>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
          <div class="col-xs-6">
              Notes
          </div>
          <!-- TODO: Link to add note form 
          <div class="col-xs-6">
              <div class="pull-right">
                <a href="">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>
              </div>
          </div>
          -->
      </div>
    </div>

  </div>
  <div class="panel-body">
    {% if step.getNotes.count > 0 %}
    <ul class="list-group">
      {% for note in step.getNotes %}
        <li class="list-group-item">{{note}}</li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no notes for this step!</p>
    {% endif %}
  </div>
</div>

{% endblock %}


plans/templates/plans/step_update.html
{% extends "main/layout.html" %}

{% block content %}

<div>
    <h1>Step Update Form</h1>
    <h2>{{ page }}: {{ step }}</h2>
</div>

<div>
    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}

plans/templates/plans/upload.html
{% extends "main/layout.html" %}

{% block content %}

<div>
    <h1>CSV Plans Upload</h1>
</div>

<div>
    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}

